name: Build and Push (node)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  workflow:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: node
      dockerfile: build/Dockerfile.node

